# Generated by Django 2.0.6 on 2018-06-09 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('fake', 'Fake News'), ('true', 'The Real Truth')], default='fake', max_length=40)),
                ('ip', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('vote_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta', models.CharField(max_length=200)),
            ],
        ),
    ]
